/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AchievementList: typeof import('./components/AchievementList.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BadgeDetail: typeof import('./components/BadgeDetail.vue')['default']
    BadgeList: typeof import('./components/BadgeList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./components/SideNav.vue')['default']
    Test: typeof import('./components/test.vue')['default']
    UserProfile: typeof import('./components/UserProfile.vue')['default']
  }
}
